# Generated by Django 2.2 on 2022-11-25 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
                ('city', models.CharField(choices=[('mos', 'Москва'), ('spb', 'Санкт-Петербург'), ('min', 'Минск'), ('ebg', 'Екатеринбург')], max_length=3, verbose_name='Город')),
                ('is_verified', models.BooleanField(verbose_name='Флаг верификации')),
                ('news_count', models.IntegerField(verbose_name='Количество опубликованных новостей')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('content', models.CharField(max_length=5000, verbose_name='Содержание')),
                ('creation_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('edit_date', models.DateField(auto_now=True, verbose_name='Дата редактирования')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('comment_text', models.CharField(max_length=500, verbose_name='Текст комментария')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.News', verbose_name='Новость')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
