# Generated by Django 2.2 on 2022-12-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-creation_date'], 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_verify', 'Может верифицировать других пол-ей'),)},
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Флаг верификации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='news_count',
            field=models.IntegerField(default=0, verbose_name='Количество опубликованных новостей'),
        ),
    ]
