# Generated by Django 2.2 on 2022-12-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_auto_20221201_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_verify', 'Может верифицировать других пол-ей'), ('is_moderator', 'Флаг модератора'))},
        ),
    ]
