# Generated by Django 2.2 on 2022-12-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_auto_20221203_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Новостной тег')),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-creation_date'], 'permissions': (('can_approve', 'Может одобрять публикацию'),), 'verbose_name_plural': 'News'},
        ),
    ]
