# Generated by Django 2.2 on 2022-12-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_auto_20221203_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_tag',
            field=models.ManyToManyField(to='app_users.Tag', verbose_name='Новостной тег'),
        ),
    ]
