# Generated by Django 2.2 on 2022-12-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_news_news_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_tag',
            field=models.ManyToManyField(null=True, to='app_users.Tag', verbose_name='Новостной тег'),
        ),
    ]
